export {Header} from './Header/Header'
export {HomeSection} from './Home/HomeSection'
export {Skills} from './Skills/Skills'
export {Projects} from './Projects/Projects'
export {Footer} from './Footer/Footer'
export {Education} from'./Education/Education'